
    SKILLS = OrderedDict([
        ("Python", {"type": "programming"}), ("Java", {"type": "programming"}), ("C++", {"type": "programming"}),
        ("JavaScript", {"type": "programming"}), ("TypeScript", {"type": "programming"}), ("C#", {"type": "programming"}),
        ("Ruby", {"type": "programming"}), ("Go", {"type": "programming"}), ("Rust", {"type": "programming"}),
        ("Swift", {"type": "programming"}), ("Kotlin", {"type": "programming"}), ("PHP", {"type": "programming"}),
        ("R", {"type": "programming"}), ("MATLAB", {"type": "programming"}), ("SQL", {"type": "database"}),
        ("NoSQL", {"type": "database"}), ("MongoDB", {"type": "database"}), ("PostgreSQL", {"type": "database"}),
        ("MySQL", {"type": "database"}), ("Oracle DB", {"type": "database"}), ("Redis", {"type": "database"}),
        ("AWS", {"type": "cloud"}), ("Azure", {"type": "cloud"}), ("GCP", {"type": "cloud"}),
        ("Docker", {"type": "devops"}), ("Kubernetes", {"type": "devops"}), ("Terraform", {"type": "devops"}),
        ("Ansible", {"type": "devops"}), ("Jenkins", {"type": "devops"}), ("CI/CD", {"type": "devops"}),
        ("Git", {"type": "devops"}), ("Linux", {"type": "system"}), ("Machine Learning", {"type": "ai"}),
        ("Deep Learning", {"type": "ai"}), ("NLP", {"type": "ai"}), ("Computer Vision", {"type": "ai"}),
        ("TensorFlow", {"type": "ai"}), ("PyTorch", {"type": "ai"}), ("Scikit-learn", {"type": "ai"}),
        ("Data Analysis", {"type": "data"}), ("Data Visualization", {"type": "data"}), ("Tableau", {"type": "data"}),
        ("Power BI", {"type": "data"}), ("Excel", {"type": "office"}), ("PowerPoint", {"type": "office"}),
        ("Word", {"type": "office"}), ("Communication", {"type": "soft"}), ("Leadership", {"type": "soft"}),
        ("Problem Solving", {"type": "soft"}), ("Critical Thinking", {"type": "soft"}),
        ("Teamwork", {"type": "soft"}), ("Time Management", {"type": "soft"}), ("Public Speaking", {"type": "soft"}),
        ("Negotiation", {"type": "soft"}), ("Financial Modeling", {"type": "finance"}),
        ("Financial Analysis", {"type": "finance"}), ("Investment Analysis", {"type": "finance"}),
        ("Risk Management", {"type": "finance"}), ("Tally ERP 9", {"type": "accounting"}),
        ("QuickBooks", {"type": "accounting"}), ("GST", {"type": "tax"}), ("Income Tax", {"type": "tax"}),
        ("Ind AS", {"type": "accounting"}), ("IFRS", {"type": "accounting"}), ("SAP HANA", {"type": "erp"}),
        ("SAP FICO", {"type": "erp"}), ("SAP MM", {"type": "erp"}), ("SAP SD", {"type": "erp"}),
        ("Salesforce", {"type": "crm"}), ("HubSpot", {"type": "crm"}), ("Zoho", {"type": "crm"}),
        ("Adobe Photoshop", {"type": "design"}), ("Illustrator", {"type": "design"}), ("Premiere Pro", {"type": "design"}),
        ("Figma", {"type": "design"}), ("Sketch", {"type": "design"}), ("Blender", {"type": "design"}),
        ("AutoCAD", {"type": "cad"}), ("SolidWorks", {"type": "cad"}), ("CATIA", {"type": "cad"}),
        ("ANSYS", {"type": "simulation"}), ("Unity", {"type": "gamedev"}), ("Unreal Engine", {"type": "gamedev"}),
        ("PLC", {"type": "automation"}), ("SCADA", {"type": "automation"}), ("DCS", {"type": "automation"}),
        ("Medical Coding", {"type": "healthcare"}), ("Medical Billing", {"type": "healthcare"}),
        ("HIPAA", {"type": "healthcare"}), ("GDPR", {"type": "compliance"}), ("Criminal Law", {"type": "legal"}),
        ("Civil Law", {"type": "legal"}), ("Constitutional Law", {"type": "legal"}),
        ("Contract Drafting", {"type": "legal"}), ("Moot Court", {"type": "legal"}),
        ("Client Counseling", {"type": "legal"}), ("Digital Marketing", {"type": "marketing"}),
        ("SEO", {"type": "marketing"}), ("SEM", {"type": "marketing"}), ("Social Media Marketing", {"type": "marketing"}),
        ("Content Marketing", {"type": "marketing"}), ("Email Marketing", {"type": "marketing"}),
        ("Google Analytics", {"type": "marketing"}), ("Project Management", {"type": "mgmt"}),
        ("Agile", {"type": "mgmt"}), ("Scrum", {"type": "mgmt"}), ("Six Sigma", {"type": "quality"}),
        ("Lean Manufacturing", {"type": "quality"}), ("TPM", {"type": "quality"}), ("Kaizen", {"type": "quality"}),
    ])
    CERTIFICATIONS = OrderedDict([
        ("AWS Certified Solutions Architect", {"domain": "Cloud"}),
        ("AWS Certified Developer", {"domain": "Cloud"}),
        ("AWS Certified SysOps", {"domain": "Cloud"}),
        ("AWS Machine Learning Specialty", {"domain": "AI/ML"}),
        ("Microsoft Azure Administrator", {"domain": "Cloud"}),
        ("Microsoft Azure AI Engineer", {"domain": "AI/ML"}),
        ("Google Cloud Architect", {"domain": "Cloud"}),
        ("Google Professional Data Engineer", {"domain": "Data"}),
        ("Google ML Engineer", {"domain": "AI/ML"}),
        ("Certified Kubernetes Administrator", {"domain": "DevOps"}),
        ("Docker Certified Associate", {"domain": "DevOps"}),
        ("Terraform Associate", {"domain": "DevOps"}),
        ("CISSP", {"domain": "Security"}),
        ("CISA", {"domain": "Security"}),
        ("CISM", {"domain": "Security"}),
        ("CompTIA Security+", {"domain": "Security"}),
        ("CompTIA CySA+", {"domain": "Security"}),
        ("CompTIA PenTest+", {"domain": "Security"}),
        ("CEH", {"domain": "Security"}),
        ("OSCP", {"domain": "Security"}),
        ("GIAC Certifications", {"domain": "Security"}),
        ("CRISC", {"domain": "Risk"}),
        ("COBIT", {"domain": "Governance"}),
        ("NIST Framework", {"domain": "Security"}),
        ("ISO 27001 Lead Auditor", {"domain": "Security"}),
        ("ISO 31000", {"domain": "Risk"}),
        ("PMP", {"domain": "ProjectMgmt"}),
        ("PMI-ACP", {"domain": "Agile"}),
        ("PMI-RMP", {"domain": "Risk"}),
        ("PMI-SP", {"domain": "Scheduling"}),
        ("PRINCE2", {"domain": "ProjectMgmt"}),
        ("Certified Scrum Master", {"domain": "Agile"}),
        ("SAFe Agilist", {"domain": "Agile"}),
        ("ITIL Foundation", {"domain": "ITSM"}),
        ("ITIL 4 Managing Professional", {"domain": "ITSM"}),
        ("ISTQB", {"domain": "Testing"}),
        ("Certified Selenium Tester", {"domain": "Testing"}),
        ("Oracle Certified Java Programmer", {"domain": "Programming"}),
        ("Oracle Certified Professional", {"domain": "Database"}),
        ("Cisco CCNA", {"domain": "Networking"}),
        ("Cisco CCNP", {"domain": "Networking"}),
        ("Cisco DevNet", {"domain": "Networking"}),
        ("Red Hat RHCE", {"domain": "Linux"}),
        ("Red Hat RHCSA", {"domain": "Linux"}),
        ("Salesforce Administrator", {"domain": "CRM"}),
        ("Salesforce Developer", {"domain": "CRM"}),
        ("HubSpot Certified", {"domain": "Marketing"}),
        ("Google Analytics Individual Qualification", {"domain": "Marketing"}),
        ("Google Ads Certification", {"domain": "Marketing"}),
        ("Facebook Blueprint", {"domain": "Marketing"}),
        ("Adobe Certified Expert", {"domain": "Design"}),
        ("Autodesk Certified Professional", {"domain": "CAD"}),
        ("Chartered Accountant (CA)", {"domain": "Accounting"}),
        ("Company Secretary (CS)", {"domain": "Corporate"}),
        ("Cost & Management Accountant (CMA)", {"domain": "Accounting"}),
        ("CFA", {"domain": "Finance"}),
        ("FRM", {"domain": "Risk"}),
        ("CFP", {"domain": "Finance"}),
        ("NISM Certifications", {"domain": "Finance"}),
        ("IFRS Certificate", {"domain": "Accounting"}),
        ("Certified Internal Auditor", {"domain": "Audit"}),
        ("NEBOSH", {"domain": "Safety"}),
        ("IOSH", {"domain": "Safety"}),
        ("HACCP", {"domain": "Food"}),
        ("FSSC 22000", {"domain": "Food"}),
        ("SOX Compliance", {"domain": "Compliance"}),
        ("AML Certification", {"domain": "Compliance"}),
        ("KYC Certification", {"domain": "Compliance"}),
        ("Six Sigma Green Belt", {"domain": "Quality"}),
        ("Six Sigma Black Belt", {"domain": "Quality"}),
        ("Lean Certification", {"domain": "Quality"}),
        ("TPM Certification", {"domain": "Quality"}),
        ("NPTEL Certifications", {"domain": "Academics"}),
        ("Coursera Specializations", {"domain": "Academics"}),
        ("Harvard edX Certificates", {"domain": "Academics"}),
    ])
    COMPANIES = OrderedDict([
        # Indian IT Services
        ("TCS", {"type": "IT Services", "indian": True}),
        ("Infosys", {"type": "IT Services", "indian": True}),
        ("Wipro", {"type": "IT Services", "indian": True}),
        ("HCL", {"type": "IT Services", "indian": True}),
        ("Tech Mahindra", {"type": "IT Services", "indian": True}),
        ("LTI Mindtree", {"type": "IT Services", "indian": True}),
        ("Mphasis", {"type": "IT Services", "indian": True}),
        ("Hexaware", {"type": "IT Services", "indian": True}),
        ("Persistent Systems", {"type": "IT Services", "indian": True}),
        ("Cognizant", {"type": "IT Services", "indian": True}),
        # MNC Tech
        ("Google India", {"type": "Product", "indian": False}),
        ("Microsoft India", {"type": "Product", "indian": False}),
        ("Amazon India", {"type": "Ecommerce", "indian": False}),
        ("Meta India", {"type": "Product", "indian": False}),
        ("Apple India", {"type": "Product", "indian": False}),
        ("Netflix India", {"type": "Media", "indian": False}),
        ("Uber India", {"type": "Product", "indian": False}),
        ("Adobe India", {"type": "Product", "indian": False}),
        ("Oracle India", {"type": "Product", "indian": False}),
        ("IBM India", {"type": "IT Services", "indian": False}),
        ("SAP India", {"type": "Product", "indian": False}),
        ("Salesforce India", {"type": "Product", "indian": False}),
        ("VMware India", {"type": "Product", "indian": False}),
        # Indian Startups / Product
        ("Flipkart", {"type": "Ecommerce", "indian": True}),
        ("Zomato", {"type": "FoodTech", "indian": True}),
        ("Swiggy", {"type": "FoodTech", "indian": True}),
        ("Paytm", {"type": "FinTech", "indian": True}),
        ("PhonePe", {"type": "FinTech", "indian": True}),
        ("Razorpay", {"type": "FinTech", "indian": True}),
        ("CRED", {"type": "FinTech", "indian": True}),
        ("Groww", {"type": "FinTech", "indian": True}),
        ("Zerodha", {"type": "FinTech", "indian": True}),
        ("Upstox", {"type": "FinTech", "indian": True}),
        ("Ola", {"type": "Mobility", "indian": True}),
        ("Rapido", {"type": "Mobility", "indian": True}),
        ("BharatPe", {"type": "FinTech", "indian": True}),
        ("Slice", {"type": "FinTech", "indian": True}),
        ("Cars24", {"type": "Ecommerce", "indian": True}),
        ("Spinny", {"type": "Ecommerce", "indian": True}),
        ("DealShare", {"type": "Ecommerce", "indian": True}),
        ("Meesho", {"type": "Ecommerce", "indian": True}),
        ("Nykaa", {"type": "Ecommerce", "indian": True}),
        ("Byju's", {"type": "EdTech", "indian": True}),
        ("Unacademy", {"type": "EdTech", "indian": True}),
        ("UpGrad", {"type": "EdTech", "indian": True}),
        ("Vedantu", {"type": "EdTech", "indian": True}),
        ("Physics Wallah", {"type": "EdTech", "indian": True}),
        ("Ola Electric", {"type": "EV", "indian": True}),
        ("Ather Energy", {"type": "EV", "indian": True}),
        ("OYO", {"type": "Hospitality", "indian": True}),
        ("MakeMyTrip", {"type": "Travel", "indian": True}),
        ("Urban Company", {"type": "Services", "indian": True}),
        ("Dunzo", {"type": "Logistics", "indian": True}),
        ("Delhivery", {"type": "Logistics", "indian": True}),
        ("Shadowfax", {"type": "Logistics", "indian": True}),
        ("Porter", {"type": "Logistics", "indian": True}),
        ("Licious", {"type": "FoodTech", "indian": True}),
        ("BigBasket", {"type": "Ecommerce", "indian": True}),
        ("Blinkit", {"type": "QuickCommerce", "indian": True}),
        ("Zepto", {"type": "QuickCommerce", "indian": True}),
        # Indian Corporates
        ("Reliance Industries", {"type": "Conglomerate", "indian": True}),
        ("Tata Group", {"type": "Conglomerate", "indian": True}),
        ("Adani Group", {"type": "Conglomerate", "indian": True}),
        ("Tata Motors", {"type": "Automobile", "indian": True}),
        ("Mahindra & Mahindra", {"type": "Automobile", "indian": True}),
        ("Maruti Suzuki", {"type": "Automobile", "indian": True}),
        ("Bajaj Auto", {"type": "Automobile", "indian": True}),
        ("TVS Motor", {"type": "Automobile", "indian": True}),
        ("L&T", {"type": "Infrastructure", "indian": True}),
        ("Godrej Group", {"type": "Conglomerate", "indian": True}),
        ("Bajaj Group", {"type": "Conglomerate", "indian": True}),
        ("Aditya Birla Group", {"type": "Conglomerate", "indian": True}),
        ("Mahindra Group", {"type": "Conglomerate", "indian": True}),
        ("RPG Group", {"type": "Conglomerate", "indian": True}),
        ("Murugappa Group", {"type": "Conglomerate", "indian": True}),
        # PSUs
        ("ONGC", {"type": "PSU"}),
        ("Indian Oil", {"type": "PSU"}),
        ("BHEL", {"type": "PSU"}),
        ("GAIL", {"type": "PSU"}),
        ("NTPC", {"type": "PSU"}),
        ("NHPC", {"type": "PSU"}),
        ("THDC", {"type": "PSU"}),
        ("SJVN", {"type": "PSU"}),
        ("IRCTC", {"type": "PSU"}),
        ("CONCOR", {"type": "PSU"}),
        ("Coal India", {"type": "PSU"}),
        ("SAIL", {"type": "PSU"}),
        ("HAL", {"type": "PSU"}),
        ("BEL", {"type": "PSU"}),
        ("ISRO", {"type": "Space"}),
        ("DRDO", {"type": "Defence Research"}),
        # Banks / Financial
        ("SBI", {"type": "PSU Bank"}),
        ("HDFC Bank", {"type": "Private Bank"}),
        ("ICICI Bank", {"type": "Private Bank"}),
        ("Axis Bank", {"type": "Private Bank"}),
        ("Kotak Mahindra Bank", {"type": "Private Bank"}),
        ("Yes Bank", {"type": "Private Bank"}),
        ("RBI", {"type": "Central Bank"}),
        ("NABARD", {"type": "Development Bank"}),
        ("SEBI", {"type": "Regulator"}),
        ("LIC", {"type": "Insurance"}),
        ("HDFC Life", {"type": "Insurance"}),
        ("ICICI Prudential", {"type": "Insurance"}),
        # MNC Industrial
        ("Siemens India", {"type": "Industrial", "indian": False}),
        ("ABB India", {"type": "Industrial", "indian": False}),
        ("Schneider Electric India", {"type": "Industrial", "indian": False}),
        ("Honeywell India", {"type": "Industrial", "indian": False}),
        ("GE India", {"type": "Industrial", "indian": False}),
        ("Philips India", {"type": "Healthcare", "indian": False}),
        ("Bosch India", {"type": "Automotive", "indian": False}),
        ("Hitachi India", {"type": "Industrial", "indian": False}),
        ("Panasonic India", {"type": "Consumer", "indian": False}),
        ("Sony India", {"type": "Consumer", "indian": False}),
        ("Samsung India", {"type": "Consumer", "indian": False}),
        ("LG India", {"type": "Consumer", "indian": False}),
        # Pharma
        ("Sun Pharma", {"type": "Pharma", "indian": True}),
        ("Dr Reddy's Labs", {"type": "Pharma", "indian": True}),
        ("Cipla", {"type": "Pharma", "indian": True}),
        ("Lupin", {"type": "Pharma", "indian": True}),
        ("Aurobindo Pharma", {"type": "Pharma", "indian": True}),
        ("Pfizer India", {"type": "Pharma", "indian": False}),
        ("Novartis India", {"type": "Pharma", "indian": False}),
        ("GSK India", {"type": "Pharma", "indian": False}),
        ("Sanofi India", {"type": "Pharma", "indian": False}),
        ("Johnson & Johnson India", {"type": "Healthcare", "indian": False}),
        # Healthcare
        ("AIIMS", {"type": "Healthcare"}),
        ("Apollo Hospitals", {"type": "Healthcare", "indian": True}),
        ("Fortis Healthcare", {"type": "Healthcare", "indian": True}),
        ("Max Healthcare", {"type": "Healthcare", "indian": True}),
        ("Narayana Health", {"type": "Healthcare", "indian": True}),
        ("Medanta Medicity", {"type": "Healthcare", "indian": True}),
        # Education
        ("IITs", {"type": "Education"}),
        ("IIMs", {"type": "Education"}),
        ("AIIMS Delhi", {"type": "Education"}),
        ("NITs", {"type": "Education"}),
        ("IISc", {"type": "Education"}),
        ("Delhi University", {"type": "Education"}),
        ("JNU", {"type": "Education"}),
        ("BITS Pilani", {"type": "Education"}),
        ("VIT", {"type": "Education"}),
        ("SRM", {"type": "Education"}),
        ("Amity University", {"type": "Education"}),
    ])
    INDUSTRIES = [
        "Information Technology", "Software Services", "IT Services", "Product",
        "Banking", "Financial Services", "Insurance", "FinTech", "InsurTech",
        "Healthcare", "Pharmaceuticals", "Medical Devices", "HealthTech",
        "Automobile", "Auto Components", "Electric Vehicles",
        "Manufacturing", "Industrial Automation", "3D Printing", "Robotics",
        "Construction", "Infrastructure", "Real Estate", "PropTech",
        "Retail", "E-commerce", "Quick Commerce", "D2C",
        "Telecom", "Media & Entertainment", "OTT", "Gaming",
        "Education", "EdTech", "E-learning",
        "Government", "Defence", "Public Sector",
        "Agriculture", "AgriTech", "Dairy", "Poultry", "Fisheries", "Food Processing",
        "Energy", "Oil & Gas", "Renewable Energy", "Solar", "Wind", "Nuclear",
        "Aerospace", "SpaceTech", "Aviation",
        "Semiconductor", "Electronics", "Consumer Electronics",
        "Cyber Security", "Cloud Computing", "Data Analytics",
        "Artificial Intelligence", "Machine Learning", "Blockchain",
        "Chemical", "Petrochemicals", "Cement", "Steel", "Aluminum",
        "Textile", "Fashion", "Apparel",
        "Paper & Pulp", "Packaging", "Plastics", "Glass",
        "Hospitality", "Tourism", "Travel",
        "Logistics", "Supply Chain", "Warehousing",
        "Mining", "Metallurgy", "Ceramic",
        "Legal", "Law Firm", "Corporate Legal",
        "Consulting", "Management Consulting", "Strategy",
        "Marketing", "Advertising", "PR",
        "HR", "Recruitment", "Staffing",
        "NGO", "Social Impact", "Rural Development",
        "Sports", "Fitness", "Wellness",
        "Climate Tech", "Waste Management", "Water Treatment",
        "Biotechnology", "Nanotechnology",
        "Printing & Publishing",
        "Security & Surveillance",
        "Facilities Management",
        "Architecture & Design",
    ]
    LEARNING_RESOURCES = [
        "NPTEL", "Coursera", "edX", "Udemy", "Udacity", "Pluralsight",
        "LinkedIn Learning", "Khan Academy", "MIT OpenCourseWare",
        "Ekeeda", "Made Easy", "Ace Academy", "Gateforum",
        "IMS", "T.I.M.E.", "Career Launcher", "Mahesh Tutorials",
        "Allen", "Aakash Institute", "Resonance", "Vibrant Academy",
        "Chahal Academy", "Vision IAS", "Insights IAS",
        "Unacademy", "Physics Wallah", "Byju's", "Vedantu",
        "Simplilearn", "Great Learning", "UpGrad", "Jio Institute",
        "W3Schools", "MDN Web Docs", "GeeksforGeeks", "Stack Overflow",
        "YouTube Tutorials", "freeCodeCamp", "The Odin Project",
        "Codecademy", "DataCamp", "Kaggle", "Analytics Vidhya",
        "Todoist", "Coding Ninjas", "Scaler Academy",
        "Pepcoding", "Apna College", "Love Babbar",
    ]
