
class Taxonomies:
    SCHOOL_STREAMS = OrderedDict([
        ("10th", {"level": EducationLevel.SCHOOL, "next": ["11th Science","11th Commerce","11th Arts","Vocational Course"]}),
        ("11th Science", {"level": EducationLevel.SCHOOL, "stream": "Science"}),
        ("11th Commerce", {"level": EducationLevel.SCHOOL, "stream": "Commerce"}),
        ("11th Arts", {"level": EducationLevel.SCHOOL, "stream": "Arts"}),
        ("12th PCM", {"level": EducationLevel.SCHOOL, "stream": "Science"}),
        ("12th PCB", {"level": EducationLevel.SCHOOL, "stream": "Science"}),
        ("12th Commerce", {"level": EducationLevel.SCHOOL, "stream": "Commerce"}),
        ("12th Arts", {"level": EducationLevel.SCHOOL, "stream": "Arts"}),
    ])
    ITI_TRADES = OrderedDict([
        ("ITI Electrician", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Electrical"}),
        ("ITI Fitter", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Mechanical"}),
        ("ITI Welder", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Fabrication"}),
        ("ITI Plumber", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Plumbing"}),
        ("ITI Carpenter", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Woodwork"}),
        ("ITI Painter", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Painting"}),
        ("ITI Machinist", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Machining"}),
        ("ITI Turner", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Turning"}),
        ("ITI COPA", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Computer"}),
        ("ITI Electronics", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Electronics"}),
        ("ITI Refrigeration", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Refrigeration"}),
        ("ITI Diesel Mechanic", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Automobile"}),
        ("ITI Motor Mechanic", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Automobile"}),
        ("ITI Solar Technician", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Renewable"}),
        ("ITI CNC Operator", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Manufacturing"}),
        ("ITI Agriculture Machinery", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Agri"}),
        ("ITI Wireman", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Electrical"}),
        ("ITI Surveyor", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Civil"}),
        ("ITI Draftsman Civil", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Civil"}),
        ("ITI Draftsman Mechanical", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Mechanical"}),
        ("ITI Horticulture", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Agriculture"}),
        ("ITI Food Processing", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Food"}),
        ("ITI Textile", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Textile"}),
        ("ITI Foundry", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Foundry"}),
        ("ITI Leather Goods", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Leather"}),
    ])
    DIPLOMAS = OrderedDict([
        ("Diploma in Computer Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "CS"}),
        ("Diploma in Mechanical Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Mechanical"}),
        ("Diploma in Civil Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Civil"}),
        ("Diploma in Electrical Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Electrical"}),
        ("Diploma in Electronics & Comm", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "EC"}),
        ("Diploma in Chemical Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Chemical"}),
        ("Diploma in Automobile Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Automobile"}),
        ("Diploma in IT", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "IT"}),
        ("Diploma in Mining Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Mining"}),
        ("Diploma in Petroleum Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Petroleum"}),
        ("Diploma in Food Technology", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Food"}),
        ("Diploma in Aeronautical Engg", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Aero"}),
        ("Diploma in Marine Engineering", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Marine"}),
        ("Diploma in Hotel Management", {"level": EducationLevel.DIPLOMA, "duration": 3, "field": "Hospitality"}),
        ("Diploma in Fashion Design", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Fashion"}),
        ("Diploma in Interior Design", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Design"}),
        ("Diploma in Pharmacy", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Pharmacy"}),
        ("Diploma in Medical Lab Tech", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Healthcare"}),
        ("Diploma in Radiology", {"level": EducationLevel.DIPLOMA, "duration": 2, "field": "Healthcare"}),
        ("Diploma in Event Management", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Mgmt"}),
        ("Diploma in Journalism", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Media"}),
        ("Diploma in Film Making", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Media"}),
        ("Diploma in Graphic Design", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Design"}),
        ("Diploma in Fire & Safety", {"level": EducationLevel.DIPLOMA, "duration": 1, "field": "Safety"}),
    ])
    UNDERGRAD_DEGREES = OrderedDict([
        ("B.Tech Computer Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech CSE AI/ML", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech CSE Data Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Cyber Security", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Electronics & Comm", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Electrical", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Mechanical", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Civil", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Automobile", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Aerospace", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Chemical", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Biotechnology", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Instrumentation", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Production", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Industrial", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Textile", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Energy", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Nanotechnology", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Mechatronics", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Metallurgical", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Mining", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Petroleum", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Marine", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Ceramic", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Tech Food Technology", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Engineering"}),
        ("B.Pharma", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Pharmacy"}),
        ("B.Sc Computer Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc IT", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Data Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Mathematics", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Physics", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Chemistry", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Biology", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Biotechnology", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Microbiology", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Environmental Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Statistics", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Actuarial Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Aviation", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Nautical Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Nursing", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Healthcare"}),
        ("B.Sc Agriculture", {"level": EducationLevel.UNDERGRADUATE, "duration": 4, "field": "Agriculture"}),
        ("B.Sc Forensic Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Science"}),
        ("B.Sc Nutrition", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Healthcare"}),
        ("B.Sc Visual Comm", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Media"}),
        ("B.Sc Fashion Technology", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Fashion"}),
        ("B.Com", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Commerce"}),
        ("B.Com (Hons)", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Commerce"}),
        ("B.Com Banking & Insurance", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Commerce"}),
        ("B.Com Financial Markets", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Commerce"}),
        ("B.Com Taxation", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Commerce"}),
        ("B.Com International Business", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Commerce"}),
        ("BBA", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Mgmt"}),
        ("BBA Business Analytics", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Mgmt"}),
        ("BBA Digital Marketing", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Mgmt"}),
        ("BBA Logistics", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Mgmt"}),
        ("BBA Healthcare Mgmt", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Mgmt"}),
        ("BBA Entrepreneurship", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Mgmt"}),
        ("BBA Retail Mgmt", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Mgmt"}),
        ("BBA Finance", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Mgmt"}),
        ("BCA", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "CompApp"}),
        ("BCA Cloud Computing", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "CompApp"}),
        ("BCA Cyber Security", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "CompApp"}),
        ("BCA Data Analytics", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "CompApp"}),
        ("BCA AI", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "CompApp"}),
        ("BA Economics", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Arts"}),
        ("BA English", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Arts"}),
        ("BA History", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Arts"}),
        ("BA Political Science", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Arts"}),
        ("BA Sociology", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Arts"}),
        ("BA Psychology", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Arts"}),
        ("BA Public Admin", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Arts"}),
        ("BA Journalism", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Media"}),
        ("BA Mass Comm", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Media"}),
        ("BA Liberal Arts", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Arts"}),
        ("BBA LLB", {"level": EducationLevel.UNDERGRADUATE, "duration": 5, "field": "Law"}),
        ("B.Com LLB", {"level": EducationLevel.UNDERGRADUATE, "duration": 5, "field": "Law"}),
        ("B.Sc LLB", {"level": EducationLevel.UNDERGRADUATE, "duration": 5, "field": "Law"}),
        ("LLB (3-year)", {"level": EducationLevel.UNDERGRADUATE, "duration": 3, "field": "Law"}),
        ("MBBS", {"level": EducationLevel.UNDERGRADUATE, "duration": 5.5, "field": "Medicine"}),
        ("BDS", {"level": EducationLevel.UNDERGRADUATE, "duration": 5, "field": "Dental"}),
        ("BAMS", {"level": EducationLevel.UNDERGRADUATE, "duration": 5.5, "field": "Ayurveda"}),
        ("BHMS", {"level": EducationLevel.UNDERGRADUATE, "duration": 5.5, "field": "Homeopathy"}),
        ("B.Arch", {"level": EducationLevel.UNDERGRADUATE, "duration": 5, "field": "Architecture"}),
    ])
    POSTGRAD_DEGREES = OrderedDict([
        ("M.Tech CSE", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Data Science", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech AI/ML", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Cyber Security", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech VLSI", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Structural", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Thermal", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Automotive", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Biomedical", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Renewable Energy", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Industrial IoT", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Tech Robotics", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Engineering"}),
        ("M.Sc Data Science", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Computer Science", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Physics", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Chemistry", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Mathematics", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Biotechnology", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Microbiology", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Environmental Science", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Astrophysics", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Bioinformatics", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Food Technology", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Nanoscience", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Forensic Science", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Science"}),
        ("M.Sc Agriculture", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Agriculture"}),
        ("M.Sc Nursing", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Healthcare"}),
        ("MCA", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "CompApp"}),
        ("MBA", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Finance", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Marketing", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA HR", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Operations", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Business Analytics", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Healthcare", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Rural Mgmt", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Agribusiness", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Hospitality", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Sports Mgmt", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Digital Transformation", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("MBA Supply Chain", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Mgmt"}),
        ("M.Com", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Commerce"}),
        ("MA Economics", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Arts"}),
        ("MA English", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Arts"}),
        ("MA Sociology", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Arts"}),
        ("MA Psychology", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Arts"}),
        ("MA Public Admin", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Arts"}),
        ("MA Journalism", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Media"}),
        ("MA Mass Comm", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Media"}),
        ("MA Social Work", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Arts"}),
        ("LLM", {"level": EducationLevel.POSTGRADUATE, "duration": 1, "field": "Law"}),
        ("MD Medicine", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MD Pediatrics", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MD Gynecology", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MD Radiology", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MD Anesthesia", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MD Dermatology", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MS General Surgery", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MS Orthopedics", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MS Ophthalmology", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("MS ENT", {"level": EducationLevel.POSTGRADUATE, "duration": 3, "field": "Medicine"}),
        ("M.Pharma", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Pharmacy"}),
        ("M.Arch", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Architecture"}),
        ("M.Plan", {"level": EducationLevel.POSTGRADUATE, "duration": 2, "field": "Planning"}),
        ("M.Lib.Sc", {"level": EducationLevel.POSTGRADUATE, "duration": 1, "field": "Library"}),
    ])
    DOCTORATES = OrderedDict([
        ("PhD Computer Science", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Engineering"}),
        ("PhD Physics", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Science"}),
        ("PhD Chemistry", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Science"}),
        ("PhD Mathematics", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Science"}),
        ("PhD Economics", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Arts"}),
        ("PhD Management", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Mgmt"}),
        ("PhD Biotechnology", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Science"}),
        ("PhD Mechanical", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Engineering"}),
        ("PhD Electrical", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Engineering"}),
        ("PhD Medicine", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Medicine"}),
        ("PhD Law", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Law"}),
        ("PhD Psychology", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Arts"}),
        ("PhD Agriculture", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Agriculture"}),
        ("PhD Pharmacy", {"level": EducationLevel.DOCTORATE, "duration": 5, "field": "Pharmacy"}),
    ])
    EXAMS = OrderedDict([
        ("JEE Main", {"exam_type": "engineering_entrance"}),
        ("JEE Advanced", {"exam_type": "engineering_entrance"}),
        ("BITSAT", {"exam_type": "engineering_entrance"}),
        ("VITEEE", {"exam_type": "engineering_entrance"}),
        ("SRMJEEE", {"exam_type": "engineering_entrance"}),
        ("COMEDK", {"exam_type": "engineering_entrance"}),
        ("MHT CET", {"exam_type": "state_engg"}),
        ("KCET", {"exam_type": "state_engg"}),
        ("AP EAMCET", {"exam_type": "state_engg"}),
        ("TS EAMCET", {"exam_type": "state_engg"}),
        ("GUJCET", {"exam_type": "state_engg"}),
        ("OJEE", {"exam_type": "state_engg"}),
        ("BCECE", {"exam_type": "state_engg"}),
        ("WBJEE", {"exam_type": "state_engg"}),
        ("CUET", {"exam_type": "university_entrance"}),
        ("MET", {"exam_type": "university_entrance"}),
        ("NPAT", {"exam_type": "university_entrance"}),
        ("SET", {"exam_type": "university_entrance"}),
        ("MUCMET", {"exam_type": "university_entrance"}),
        ("NEET", {"exam_type": "medical_entrance"}),
        ("NEET PG", {"exam_type": "medical_postgrad"}),
        ("AIIMS", {"exam_type": "medical_entrance"}),
        ("JIPMER", {"exam_type": "medical_entrance"}),
        ("MCAT", {"exam_type": "international_medical"}),
        ("USMLE", {"exam_type": "international_medical"}),
        ("PLAB", {"exam_type": "international_medical"}),
        ("CAT", {"exam_type": "management_entrance"}),
        ("XAT", {"exam_type": "management_entrance"}),
        ("SNAP", {"exam_type": "management_entrance"}),
        ("NMAT", {"exam_type": "management_entrance"}),
        ("IIFT", {"exam_type": "management_entrance"}),
        ("CMAT", {"exam_type": "management_entrance"}),
        ("MAT", {"exam_type": "management_entrance"}),
        ("GMAT", {"exam_type": "international_mba"}),
        ("GATE", {"exam_type": "engineering_postgrad"}),
        ("UPSC CSE", {"exam_type": "civil_services"}),
        ("UPSC CAPF", {"exam_type": "civil_services"}),
        ("UPSC EPFO", {"exam_type": "civil_services"}),
        ("State PSC", {"exam_type": "state_civil_services"}),
        ("SSC CGL", {"exam_type": "staff_selection"}),
        ("SSC JE", {"exam_type": "staff_selection"}),
        ("SSC CHSL", {"exam_type": "staff_selection"}),
        ("IBPS PO", {"exam_type": "banking"}),
        ("IBPS Clerk", {"exam_type": "banking"}),
        ("IBPS SO", {"exam_type": "banking"}),
        ("SBI PO", {"exam_type": "banking"}),
        ("SBI Clerk", {"exam_type": "banking"}),
        ("RBI Grade B", {"exam_type": "banking"}),
        ("RBI Assistant", {"exam_type": "banking"}),
        ("NABARD Grade A", {"exam_type": "banking"}),
        ("SEBI Grade A", {"exam_type": "finance"}),
        ("LIC AAO", {"exam_type": "insurance"}),
        ("NICL AO", {"exam_type": "insurance"}),
        ("RRB NTPC", {"exam_type": "railway"}),
        ("RRB ALP", {"exam_type": "railway"}),
        ("RRB Technician", {"exam_type": "railway"}),
        ("CLAT", {"exam_type": "law_entrance"}),
        ("AILET", {"exam_type": "law_entrance"}),
        ("LSAT", {"exam_type": "law_entrance"}),
        ("CA Foundation", {"exam_type": "ca_entrance"}),
        ("CS Foundation", {"exam_type": "cs_entrance"}),
        ("CMA Foundation", {"exam_type": "cma_entrance"}),
        ("NIFT", {"exam_type": "design_entrance"}),
        ("NID DAT", {"exam_type": "design_entrance"}),
        ("CEED", {"exam_type": "design_postgrad"}),
        ("UGC NET", {"exam_type": "academic"}),
        ("GRE", {"exam_type": "international_ms"}),
        ("IELTS", {"exam_type": "english_proficiency"}),
        ("TOEFL", {"exam_type": "english_proficiency"}),
        ("PTE", {"exam_type": "english_proficiency"}),
        ("OET", {"exam_type": "english_proficiency"}),
        ("NCHM JEE", {"exam_type": "hotel_entrance"}),
        ("DU JAT", {"exam_type": "university_entrance"}),
        ("FTII Entrance", {"exam_type": "film_entrance"}),
        ("SRFTI", {"exam_type": "film_entrance"}),
        ("CTET", {"exam_type": "teaching"}),
        ("DSSSB", {"exam_type": "teaching"}),
        ("KVS", {"exam_type": "teaching"}),
        ("NVS", {"exam_type": "teaching"}),
    ])
